### ISSUE TITLE
How to use strategy generator

### ISSUE THREAD

**Issue by softwareklinic** [andresilvasantos/bitprophet#1]
Does it create the code for new strategy.. since the strategies you have provided in README there no relevant modules in the strategies folder...

**Comment by d4r1as** [comment]
This is not a code issue. Just code your own strategy based on the files in the strategy directory.

**Comment by andresilvasantos** [comment]
@softwareklinic 

Let's say you want to create the strategy __Money Maker__.

Create a new folder inside your project root folder with the name __strategies__ for example.
Add the following option to BitProphet init:
```
strategiesDir: "./strategies"
```
Inside that folder, create an __index.js__ file with the following code:
```
module.exports = {
    strategies: {
        moneymaker: {
            name: "Money Maker",
            targetMarket: "BTC",
            paperTrading: true, //It will simulate trades only
            buyAmountMarket: 0.018, //BTC in this case
            profitTarget: 1.4, //%
            maxLoss: 0.8, //%
        }
    }
}
```
Create a file inside that folder with the id of your new strategy __moneymaker.js__.

Code it following the examples inside the [strategies](https://github.com/andresilvasantos/bitprophet/tree/master/strategies) folder and check the [indicators file](https://github.com/andresilvasantos/bitprophet/blob/master/indicators.js) to see which indicators you can use.

The following is the base code of any strategy.
You first do validation to remove pairs that are far from what you want to trade. Since we are processing each pair each second, it is important for efficiency, to reduce the number of watching pairs. Lets say, you only want to trade pairs that have a volume above 500BTC in the past 24 hours. It's very likely that the 24h volume won't change that fast, so you do that check in validation.

```
var bp = require('bitprophet')

var intervalsValidation = ["1h"] //The intervals you need to validate each pair
var intervalsWatch = ["15m", "5m"] //The intervals you'll need to trade the pair

module.exports = {
    resetPairCustomData: function(pair) {
        //Setup here custom vars for each pair
        pair.myvar = 0
    },
    checkValidWorkingPair: function(strategy, pair) {
        function setPairValid(valid) {
            if(valid) {
                if(pair.status == -1) pair.functions.addWatcherChartUpdates(intervalsWatch)
                pair.status = 0
            }
            else {
                if(pair.status == 0) pair.functions.removeWatcherChartUpdates(intervalsWatch)
                pair.status = -1
            }
        }

        //This will make sure the intervals you request for validation are updated
        if(pair.functions.chartsNeedUpdate(intervalsValidation, 60, true)) return

        pair.lastValidCheck = Date.now()

        //YOUR CODE HERE

        setPairValid(/*condition*/)
    },
    process: function(strategy, pair) {
        //This will make sure the intervals you request for trading are updated
        if(!pair.functions.chartUpdatesActive(intervalsWatch)) {
            pair.functions.ensureChartUpdates(intervalsWatch)
            return
        }

        //YOUR CODE
}
```

**Comment by softwareklinic** [comment]
Agree -- its not a code issue - just wanted to see whats the purpose of strategy_generator.... im neither a node.js expert nor finance background on creating strategies... so wanted to see if you have more strategies already that can be shared... in the repo

**Comment by andresilvasantos** [comment]
Not a problem!

So, __strategy_manager.js__ uses __strategy_generator.js__ to instantiate new strategy objects when BitProphet starts, based on the settings and source code you provide for each one. So yes, it generates strategies, but probably not in the way you're expecting.

I'll share a few more strategies with different use cases soon. I just have to update their code to be running with the new BitProphet's version.

You can always check the code for the alerts ([Alerts RSI](https://github.com/andresilvasantos/bitprophet/blob/master/strategies/alertsrsi.js) for example) and try to change it in a way that will help you trade. They are very simple to understand and they will just send alerts to Telegram based on the indicators you choose. Tweak them to fit your needs.

**Comment by softwareklinic** [comment]
ty Andre

**Comment by softwareklinic** [comment]
also ichimoku how should i read eg. below

:information_source: Alerts Ichimoku: #XVG/BTC @0.00000863 crossed 15m cloud
:information_source: Alerts Ichimoku: #CDT/BTC @0.00000652 crossed 15m cloud

I was reading about it and says --- if its above or below the cloud for bullish or bearish -- here crossed 15m cloud -- what does it mean? is it bullish or bearish

**Comment by andresilvasantos** [comment]
It is crossing above the cloud, a bullish signal.

If you check the code:
```
if(... && lastClose > ichiLead1_1h && lastClose > ichiLead2_1h && ...)
```
__lastClose__ is the last price and __ichiLead1_1h__ and __ichiLead2_1h__ are both the lines that form the cloud.

If you wanted a bearish signal you just need to change the **>** sign into **<**:
```
if(lastClose < ichiLead1_1h && lastClose < ichiLead2_1h) {
       //Send message
}

if(lastClose < ichiLead1_15m && lastClose < ichiLead2_15m) {
       //Send message
}
```
