### ISSUE TITLE
Setup Q/A

### ISSUE THREAD

**Issue by bitcoiniodev** [andresilvasantos/bitprophet#29]
Getting this error on start:
```
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. internal/modules/cjs/loader.js:702:30
WTF
```
[Description of the bug or feature]

Telegram receives start message, but no response arrive on any command

**Comment by andresilvasantos** [comment]
That is just a warning, but I fixed it just now (0.6.19), so please update your package.

The `WTF` print, was a message that I forgot to remove. :smile: 
But as it was inside the `listenToChatId` function, I know you didn't start bitprophet.

So, you'll need to:
* Say something in Telegram;
* Check the reply for the chat id;
* Update the code with the chat id and change `bitprophet.listenToChatId()` to `bitprophet.start()`;
* Run again the app.

**Comment by bitcoiniodev** [comment]
Thanks! 
If I enable paper trading - will it simulate on the  empty account? (Sorry for asking here)

UPDATE: Yes, it simulates, but shows profit only in percent, adding "0 BTC" at the end. So it looks like "5% | 0.0 BTC"

**Comment by bitcoiniodev** [comment]
What should I put inside var.js if i want to trade on all BTC pairs ? "pairs : ['BTC']" ? Could you provide some samples?

**Comment by andresilvasantos** [comment]
> If I enable paper trading - will it simulate on the empty account? (Sorry for asking here)

Yes, at least it should. If you have any problems, let me know.

> What should I put inside var.js if i want to trade on all BTC pairs ? "pairs : ['BTC']" ?

You don't need to change anything in `vars.js`. You'll need to update the `strategies/index.js` file and the `strategies/mystrategy.js`.

In index.js you'll add this:

```
mystrategy: {
	name: "My Strategy",
	paperTrading: true,
	buyAmountMarket: 0.02,
	profitTarget: 2.4,
	maxLoss: 0.8,
	maxTradingPairs: 5,
	targetMarket: "BTC"
}
```

And then create a mystrategy.js inside the same folder, you can check buydip.js to see what you can do and start from there.

**Comment by bitcoiniodev** [comment]
Thank You Andre! Cool bot actually and very smart buydip strategy. Is it possible to disable trailing stop? It often silly flushes all the profits and after that price go up and up

**Comment by bitcoiniodev** [comment]
When I set "buyAmountMarket: 0.02" - does it use this amount for each trade pair or it's a total limit of funds involved in the trades?

**Comment by andresilvasantos** [comment]
>  Is it possible to disable trailing stop? It often silly flushes all the profits and after that price go up and up

Yes, it is possible to disable and to adjust the trailing. You'll have to edit the buydip.js or your strategy file. In the last lines of code of buydip.js you'll find:

`var activateStopLoss = strategy.manageStopLoss(pair, lastClose, 2, 0.006)`

The 3rd parameter of `manageStopLoss` lets you customize how stop loss trailing behave.

* 0 - Trailing is disabled;
* 1 - Adjusts the stop loss to the price it bought if the current price goes up according to the value of the 4th parameter. It is a single time adjustment;
* 2 - Continually adjusts the stop loss, behaving like a real trailing profits.

The 4th parameter is the diff proportion from the current price to the bought price in order to activate the trailing profits. By default it is configured to 0.006 -> 0.6% which is a low value, yes.

So, you can play with those and see what suits you best.

Three examples:

```
// Deactivate stop loss adjustment at all
var activateStopLoss = strategy.manageStopLoss(pair, lastClose, 0)
```

```
// Only adjusts stop loss if price goes up 1.5%.
var activateStopLoss = strategy.manageStopLoss(pair, lastClose, 2, 0.015)
```

```
// Only adjusts stop loss one time to protect from losses, only if price goes up 1% from price bought.
var activateStopLoss = strategy.manageStopLoss(pair, lastClose, 1, 0.01)
```

> When I set "buyAmountMarket: 0.02" - does it use this amount for each trade pair or it's a total limit of funds involved in the trades?

It will use that amount for each trading pair of that strategy.

**Comment by andresilvasantos** [comment]
I'll close this issue for now. If you have more questions, feel free to comment and I'll open it again.
